name: Android CI
on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17.0.8.1'
          check-latest: 'true'
      - uses: gradle/gradle-build-action@main
        with:
          gradle-version: 7.6.1
      - name: Build JRE JAR files
        run: |
          ./scripts/languagelist_updater.sh
          mkdir out
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon
      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleDebug
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug.apk  
      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: app-debug-noruntime
          path: out/app-debug.*
